version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: gradle build
      - - save_cache:
            paths:
              - ~/.gradle
            key: gradle-{{ checksum "build.gradle" }}
      - run: gradle test