version: 2.1

jobs:
  build:

    working_directory: ~/rest-api-sample

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: gradle assemble
      - run: gradle run
      - run: gradle test
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}