version: 2.1

jobs:
  build:

    working_directory: ~/rest-api-sample

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - run: gradle build

      - run: gradle test